#!/usr/bin/env python3
"""Write a C header that tells Oscar64 where a KickAssembler blob lives.

usage: gen-asm-header.py asm.log asm.vs asm.bin asm.h

asm.log is KickAssembler's console output: its "Memory Map" lines give the
lowest address the blob starts at. asm.vs is the -vicesymbols file: every
top-level label becomes ASM_<LABEL> (upper case). asm.bin is the -binfile
output, raw bytes from that lowest address, so ASM_END = ASM_ORG + its size.
Labels inside a scope (a dot in the name) and local !-labels are skipped.
"""
import os
import re
import sys


def main() -> int:
    log, vs, binf, out = sys.argv[1:5]
    starts = [int(m.group(1), 16) for m in re.finditer(r"\$([0-9a-fA-F]{4})-\$[0-9a-fA-F]{4}", open(log).read())]
    if not starts:
        print(f"gen-asm-header: no memory map in {log}; is KickAssembler's output complete?", file=sys.stderr)
        return 1
    org = min(starts)
    size = os.path.getsize(binf)
    lines = [
        "// Generated by gen-asm-header.py from the KickAssembler build. Do not edit.",
        "#ifndef ASM_H",
        "#define ASM_H",
        f"#define ASM_ORG 0x{org:04x}",
        f"#define ASM_END 0x{org + size:04x}",
        f"#define ASM_SIZE {size}",
    ]
    seen = set()
    for line in open(vs):
        m = re.match(r"al C:([0-9a-fA-F]+) \.(\w+)$", line.strip())
        if not m:
            continue
        name = "ASM_" + m.group(2).upper()
        if name in seen or name in ("ASM_ORG", "ASM_END", "ASM_SIZE", "ASM_H"):
            continue
        seen.add(name)
        lines.append(f"#define {name} 0x{int(m.group(1), 16):04x}")
    lines.append("#endif")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
