/**
 * The walk (kernal-walk.ts) against the KERNAL reference page: which H3 is
 * which jump-table slot, what its `**Clobbers zero page:**` (may) line
 * should say, and where the page disagrees.
 */
import {
  CLOBBERS_LABEL,
  CLOBBERS_LINE,
  formatClobberRanges,
  formatClobbers,
  parseClobbers,
  type KernalClobbers,
} from "../../src/graph/kernal-clobbers.ts";
import {
  JUMP_TABLE_SLOTS,
  KernalWalker,
  hex4,
  toRanges,
  vectorDefaults,
  type WalkResult,
} from "./kernal-walk.ts";
import { group } from "./markdown.ts";

export const KERNAL_PAGE = "docs/hardware/kernal-routines-reference.md";

const ROUTINE_H3 = /^### \$([0-9A-F]{4}) — ([A-Z][A-Z0-9_]+) — .*$/gm;

interface RoutineWalk {
  name: string;
  slot: string;
  line: string;
  bytes: string[];
  unresolved: string[];
  followed: string[];
  pointerStores: string[];
  outside: string[];
  unboundedIndex: string[];
  badOpcode: string[];
  instructions: number;
}

export interface WalkAll {
  routines: RoutineWalk[];
  /** The IRQ and NMI service entries, which no jump-table routine is. */
  services: RoutineWalk[];
  /** Jump-table slots with no H3 on the page. */
  missingSlots: string[];
  vectors: Record<string, string>;
}

const $4 = (n: number) => `$${hex4(n)}`;
const $2 = (n: number) => `$${n.toString(16).toUpperCase().padStart(2, "0")}`;

/** The may line for one walk result. */
function mayClobbers(r: WalkResult, from: string): KernalClobbers {
  const notes = [`ROM walk from ${from}`];
  if (r.unresolved.size > 0)
    notes.push(
      `not followed: ${[...r.unresolved]
        .sort((a, b) => a - b)
        .map((v) => `JMP (${$4(v)})`)
        .join(", ")}`,
    );
  if (r.pointerStores.size > 0)
    notes.push(
      `also stores through ${[...r.pointerStores]
        .sort((a, b) => a - b)
        .map((p) => `(${$2(p)})`)
        .join(", ")}`,
    );
  return { ranges: toRanges(r.bytes), bound: "may", basis: notes.join("; ") };
}

function summarise(name: string, from: number, r: WalkResult): RoutineWalk {
  const sortHex = (s: Set<number>, f: (n: number) => string) => [...s].sort((a, b) => a - b).map(f);
  return {
    name,
    slot: $4(from),
    line: formatClobbers(mayClobbers(r, $4(from))),
    bytes: sortHex(r.bytes, $2),
    unresolved: sortHex(r.unresolved, $4),
    followed: sortHex(r.followed, $4),
    pointerStores: sortHex(r.pointerStores, $2),
    outside: sortHex(r.outside, $4),
    unboundedIndex: sortHex(r.unboundedIndex, $4),
    badOpcode: sortHex(r.badOpcode, $4),
    instructions: r.instructions,
  };
}

/** Routine H3s on the page, by jump-table address. */
function pageRoutines(page: string): Map<number, string> {
  const out = new Map<number, string>();
  for (const m of page.matchAll(ROUTINE_H3)) out.set(parseInt(group(m, 1), 16), group(m, 2));
  return out;
}

// The hardware IRQ entry ($FF48 pushes the registers and JMP ($0314)) and
// the NMI entry ($FE43, JMP ($0318)): walked from the ROM entry so the
// default vector is followed and counted as such.
const SERVICES: readonly [string, number][] = [
  ["IRQ", 0xff48],
  ["NMI", 0xfe43],
];

export function walkAll(rom: Buffer, page: string): WalkAll {
  const walker = new KernalWalker(rom);
  const names = pageRoutines(page);
  const routines: RoutineWalk[] = [];
  const missingSlots: string[] = [];
  for (const slot of JUMP_TABLE_SLOTS) {
    const name = names.get(slot);
    if (!name) missingSlots.push($4(slot));
    else routines.push(summarise(name, slot, walker.walk(slot)));
  }
  const services = SERVICES.map(([name, at]) => summarise(name, at, walker.walk(at)));
  const vectors: Record<string, string> = {};
  for (const [v, d] of vectorDefaults(rom)) vectors[$4(v)] = `${$4(d.target)} (${d.source})`;
  return { routines, services, missingSlots, vectors };
}

/** The H3 section bounds of a routine: from its heading to the next H2/H3. */
function sectionOf(page: string, slot: string): { start: number; end: number } | null {
  const head = page.indexOf(`### ${slot} — `);
  if (head < 0) return null;
  const next = /^#{2,3} /gm;
  next.lastIndex = head + 4;
  const m = next.exec(page);
  return { start: head, end: m ? m.index : page.length };
}

const BLOCK_BEGIN = "<!-- kernal-zp-walk: services (generated by scripts/kernal-zp-walk.ts --write) -->";
const BLOCK_END = "<!-- /kernal-zp-walk -->";
const SERVICE_ROWS: Record<string, string> = {
  IRQ: "IRQ `$FF48`, through `$0314` to `$EA31`",
  NMI: "NMI `$FE43`, through `$0318` to `$FE47`",
};

/** Bytes $02-$FF no walk writes, leaving out RAMTAS (it clears $02-$FF at cold start). */
function neverWritten(walk: WalkAll): [number, number][] {
  const written = new Set<string>();
  for (const r of [...walk.routines, ...walk.services])
    if (r.name !== "RAMTAS") for (const b of r.bytes) written.add(b);
  return toRanges(Array.from({ length: 254 }, (_, i) => i + 2).filter((b) => !written.has($2(b))));
}

/** The generated table of the IRQ and NMI service walks, and the bytes no walk writes. */
function servicesBlock(walk: WalkAll): string {
  const rows = walk.services.map((r) => `| ${SERVICE_ROWS[r.name] ?? r.name} | ${r.line} |`);
  const free = formatClobberRanges(neverWritten(walk));
  return [
    BLOCK_BEGIN,
    "| Entry | May write |",
    "|---|---|",
    ...rows,
    "",
    `No jump-table routine but RAMTAS, and neither service, may write ${free}.`,
    BLOCK_END,
  ].join("\n");
}

function blockBounds(page: string): { start: number; end: number } | null {
  const start = page.indexOf(BLOCK_BEGIN);
  const end = page.indexOf(BLOCK_END);
  return start < 0 || end < start ? null : { start, end: end + BLOCK_END.length };
}

/** The page with each routine's may line set to the walk's; inserted after **Affects:** when absent. */
export function applyWalkToPage(page: string, walk: WalkAll): string {
  const block = blockBounds(page);
  let out = block ? page.slice(0, block.start) + servicesBlock(walk) + page.slice(block.end) : page;
  for (const r of walk.routines) {
    const sec = sectionOf(out, r.slot);
    if (!sec) continue;
    const body = out.slice(sec.start, sec.end);
    const line = `${CLOBBERS_LABEL} ${r.line}`;
    const may = /^\*\*Clobbers zero page:\*\*.*\(may;.*$/m;
    let next: string;
    if (may.test(body)) next = body.replace(may, line);
    else {
      const anchor = /^\*\*Affects:\*\*.*$/m.exec(body) ?? /^### .*$/m.exec(body);
      const at = anchor ? anchor.index + anchor[0].length : 0;
      next = `${body.slice(0, at)}\n${line}${body.slice(at)}`;
    }
    out = out.slice(0, sec.start) + next + out.slice(sec.end);
  }
  return out;
}

/** A routine section's disagreements: its lines against the walk's may line and may set. */
function routineDisagreements(r: RoutineWalk, body: string): string[] {
  const bad: string[] = [];
  const parsed = [...body.matchAll(CLOBBERS_LINE)].map((m) => ({
    l: group(m, 1),
    c: parseClobbers(group(m, 1)),
  }));
  const good: { l: string; c: KernalClobbers }[] = [];
  for (const { l, c } of parsed) {
    if ("error" in c) bad.push(`${r.name}: ${c.error} in "${l}"`);
    else good.push({ l, c });
  }
  const mays = good.filter(({ c }) => c.bound === "may");
  if (mays.length !== 1)
    return [
      ...bad,
      `${r.name}: expected one (may; ...) line, found ${mays.length}; the walk says: ${r.line}`,
    ];
  if (mays[0]?.l !== r.line) bad.push(`${r.name}: page says "${mays[0]?.l}", the walk says "${r.line}"`);
  const mayBytes = new Set(r.bytes);
  const mustBytes = good
    .filter(({ c }) => c.bound === "must")
    .flatMap(({ c }) => c.ranges.flatMap(([a, b]) => Array.from({ length: b - a + 1 }, (_, i) => $2(a + i))));
  for (const b of new Set(mustBytes))
    if (!mayBytes.has(b)) bad.push(`${r.name}: must byte ${b} is outside the walk's may set`);
  return bad;
}

/** Every way the page differs from the walk: a missing, different or unparsable line, a must set outside the may set. */
export function pageDisagreements(page: string, walk: WalkAll): string[] {
  const bad: string[] = walk.missingSlots.map((s) => `${s}: jump-table slot has no routine H3 on the page`);
  const block = blockBounds(page);
  if (!block) bad.push(`the IRQ/NMI block (${BLOCK_BEGIN}) is missing`);
  else if (page.slice(block.start, block.end) !== servicesBlock(walk))
    bad.push("the IRQ/NMI table disagrees with the walk");
  for (const r of walk.routines) {
    const sec = sectionOf(page, r.slot);
    if (sec) bad.push(...routineDisagreements(r, page.slice(sec.start, sec.end)));
  }
  return bad;
}

export function walkReport(walk: WalkAll): string {
  const rows = [...walk.routines, ...walk.services].map((r) => {
    const flags = [
      r.unresolved.length ? `unresolved ${r.unresolved.join(" ")}` : "",
      r.followed.length ? `via ${r.followed.join(" ")}` : "",
      r.outside.length ? `outside ${r.outside.join(" ")}` : "",
      r.unboundedIndex.length ? `UNBOUNDED INDEX ${r.unboundedIndex.join(" ")}` : "",
      r.badOpcode.length ? `BAD OPCODE ${r.badOpcode.join(" ")}` : "",
    ].filter(Boolean);
    return `${r.name.padEnd(7)} ${r.slot} ${String(r.instructions).padStart(4)} instr ${String(r.bytes.length).padStart(3)} bytes  ${r.line}${flags.length ? `  [${flags.join("; ")}]` : ""}`;
  });
  const vec = Object.entries(walk.vectors).map(([v, t]) => `  ${v} -> ${t}`);
  const missing = walk.missingSlots.length ? [`missing H3 for ${walk.missingSlots.join(" ")}`] : [];
  return [...rows, "vectors followed through their power-on values:", ...vec, ...missing].join("\n");
}
