#!/usr/bin/env python3
"""Write a C header that tells Oscar64 where a KickAssembler blob lives.

usage: gen-asm-header.py asm.log asm.sym asm.bin asm.h

asm.log is KickAssembler's console output: its "Memory Map" lines give the
lowest address the blob starts at. asm.sym is KickAssembler's symbol file,
which keeps the scope tree (`.label math=$906 { .label sub1=$906 }`):
a top-level label becomes ASM_<LABEL>, a label inside a scope or namespace
ASM_<SCOPE>_<LABEL>, all upper case. Local !-labels are not in the file.
asm.bin is the -binfile output, raw bytes from that lowest address, so
ASM_END = ASM_ORG + its size.

Exit 1, writing nothing, when two labels give the same name (they differ only
in case, or a scope and a label join to the same text) or a label takes one
of the names the header defines itself (ASM_ORG, ASM_END, ASM_SIZE, ASM_H).

The header carries an #error for a blob that starts below $0880: Oscar64's
startup code runs from $0801 to $0880 on the c64 target, and the linker lets
a region overlap it without a message (the program then never starts).
"""
import os
import re
import sys

RESERVED = {"ASM_ORG", "ASM_END", "ASM_SIZE", "ASM_H"}
LOWEST = 0x0880


def read_symbols(path: str):
    """(name, address) for every label, name = scope path joined by '_'."""
    scopes, out = [], []
    for raw in open(path):
        line = raw.strip()
        if line == "}":
            if scopes:
                scopes.pop()
            continue
        m = re.match(r"\.label\s+(\w+)\s*=\s*\$([0-9a-fA-F]+)\s*(\{)?$", line)
        if m:
            out.append(("_".join(scopes + [m.group(1)]), int(m.group(2), 16)))
            if m.group(3):
                scopes.append(m.group(1))
            continue
        m = re.match(r"\.namespace\s+(\w+)\s*\{$", line)
        if m:
            scopes.append(m.group(1))
            continue
        if line.endswith("{"):  # any other scoped entry: keep the nesting right
            scopes.append(re.sub(r"\W+", "_", line.split("=")[0].split()[-1]))
    return out


def main() -> int:
    log, sym, binf, out = sys.argv[1:5]
    starts = [int(m.group(1), 16) for m in re.finditer(r"\$([0-9a-fA-F]{4})-\$[0-9a-fA-F]{4}", open(log).read())]
    if not starts:
        print(f"gen-asm-header: no memory map in {log}; is KickAssembler's output complete?", file=sys.stderr)
        return 1
    org = min(starts)
    size = os.path.getsize(binf)
    names: dict[str, tuple[str, int]] = {}
    errors = []
    for label, addr in read_symbols(sym):
        name = "ASM_" + label.upper()
        if name in RESERVED:
            errors.append(f"label '{label}' would define {name}, which the header defines itself; rename it")
        elif name in names and names[name][0] != label:
            errors.append(f"labels '{names[name][0]}' and '{label}' both become {name}; rename one")
        else:
            names[name] = (label, addr)
    if errors:
        for e in errors:
            print(f"gen-asm-header: {e}", file=sys.stderr)
        return 1
    lines = [
        "// Generated by gen-asm-header.py from the KickAssembler build. Do not edit.",
        "#ifndef ASM_H",
        "#define ASM_H",
        f"#define ASM_ORG 0x{org:04x}",
        f"#define ASM_END 0x{org + size:04x}",
        f"#define ASM_SIZE {size}",
        f"#if ASM_ORG < 0x{LOWEST:04x}",
        '#error "the KickAssembler blob starts below $0880, over the Oscar64 startup code: raise its * = address"',
        "#endif",
    ]
    for name in sorted(names):
        lines.append(f"#define {name} 0x{names[name][1]:04x}")
    lines.append("#endif")
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
